### ISSUE TITLE
Can't resolve import?

### ISSUE THREAD

**Issue by rmaes4** [BradenM/micropy-cli#103]
Thank you for this project. I am a novice when it comes to micropython and I found your tool to help me get going quickly. I am trying to use the micropython bluetooth library. VS Code is giving me an error however saying that it cannot be found. I tried running `micropy install bluetooth` as well but it said it could not be found. What exactly do I need to do to use the bluetooth library. Please see the screenshot below. Thanks again.
<img width="1323" alt="Screen Shot 2020-04-18 at 4 11 17 PM" src="https://user-images.githubusercontent.com/941516/79671407-a95d6c80-818f-11ea-8f8e-e3894f227802.png">

**Comment by BradenM** [comment]
Hi @rmaes4 , sorry for the delay!

This is a known issue, please see BradenM/micropy-stubs#9 for more info. Thanks!

**Comment by askpatrickw** [comment]
I opened an issue in the appropriate repo to track this: https://github.com/Josverl/micropython-stubber/issues/13

**Comment by BradenM** [comment]
Closed in https://github.com/Josverl/micropython-stubber/issues/13
