### ISSUE TITLE
src/lib is ignored from version control

### ISSUE THREAD

**Issue by askpatrickw** [BradenM/micropy-cli#135]
Just docing this so if other people hit it. The fix is super easy.

**Describe the bug**
src/lib is ignored by version control

**Expected Behavior**
files added to src/lib should be checked in.

**Current Behavior**
They are ignored.

**Work Around && Fix **

add `!src/lib` to bottom of .gitignore

**Comment by BradenM** [comment]
Actually, with the mindset of "src/lib" == 3rd party dependencies, this was on purpose. 

Ideally, I'd like to have micropy rebuild this per person from the micropy.json file ( as it does currently with the .micropy/ stubs and such). 

Do you have different intentions in mind?

**Comment by askpatrickw** [comment]
Unfortunately, many (most?) MicroPython libraries can only be manually copied into a project.
People just don't go through the steps to publish them as packages.

That was my thinking.

**Comment by BradenM** [comment]
Ah, I gotcha. 

What do you think about being able to install packages directly from git instead?

Something like:
   `micropy install  git+https://github.com/user/project.git#egg=project`

**Comment by askpatrickw** [comment]
I'm aware of all these ways to manage code.

If you don't want to take the PR, that's cool, its just a suggestion.
