### ISSUE TITLE
What is the "source" of the available stubs micropy is offering to the user ?

### ISSUE THREAD

**Issue by mibcat** [BradenM/micropy-cli#227]
Hi !

I want to get rid of the _unable to import_ error message in VSC for the bluetooth module:
![image](https://user-images.githubusercontent.com/3083162/108595428-15949800-7380-11eb-8ccb-120029c30c68.png)

I saw that there was a fix für micropython 1.13 but I'm not able to add this version because it's not listed: 

```bash
> micropy stubs search esp32

MicroPy  Searching Stub Repositories...

MicroPy  Results for esp32:
MicroPy  esp32-micropython-1.10.0
MicroPy  esp32-micropython-1.11.0
MicroPy  esp32-micropython-1.12.0 (Installed)
MicroPy  esp32-micropython-1.9.4
MicroPy  esp32-pycopy-1.11.0
MicroPy  esp32-pycopy-2.11.0.1
MicroPy  esp32-pycopy-2.11.0.5
MicroPy  esp32-pycopy-3.0.0
MicroPy  esp32_LoBo
MicroPy  esp32_LoBo-esp32_LoBo-3.2.24
```

How can I add this specific stub version ?

Thanks !

**Comment by BradenM** [comment]
Hi @mibcat -- sorry for my late reply. 

This is actually related to https://github.com/BradenM/micropy-stubs/issues/9

Newer versions of `micropython-stubber` now have the module (as of https://github.com/Josverl/micropython-stubber/issues/13).

I am looking into updating micropy-cli to utilize the latest version soon. Thanks.
