### ISSUE TITLE
Micropy 3.6 unavailable with pip on Python 3.10

### ISSUE THREAD

**Issue by bereldhuin** [BradenM/micropy-cli#298]
Hi,

I'm unable to unstall micropy 3.6 via pip on Python 3.10 (only 3.4.0 is available). 
Looking in tar.gz on pypi.org, it seems that this version is limited to Python <3.10 (whereas version 3.4 is limited to Python < 4)

PKG-INFO for micropy 3.4.0 : 
`Requires-Python: >=3.6,<4.0`

PKG-INFO for micropy 3.6.0 : 
`Requires-Python: >=3.6.2,<3.10`

**Comment by BradenM** [comment]
Hi @bereldhuin, 

`micropy-cli` "officially" supports python 3.10 in the upcoming v4.0.0 release. 

You can install the [latest release candidate](https://pypi.org/project/micropy-cli/4.0.0rc2/) (`v4.0.0-rc.2`) via `pip install  micropy-cli --upgrade  --pre`.

If you choose to do so, please let me know if you run into any issues. Thanks!
