### ISSUE TITLE
Question about non-VS Code support and board support

### ISSUE THREAD

**Issue by vincentchov** [BradenM/micropy-cli#301]
Sorry if this the wrong place to ask questions, but is the Micropy CLI compatible with other text editors like NeoVim? Also, are the stubs compatible with the ESP8266? Thanks!

Also I made a post under the Discussion section (#302), but it doesn't look like the Discussion section is used

**Comment by vincentchov** [comment]
Also I made a post under the Discussion section (#302), but it doesn't look like the Discussion section is used

**Comment by BradenM** [comment]
Closed in favor of discussion #302
