### ISSUE TITLE
"int", "str", "bytes", etc. not defined

### ISSUE THREAD

**Issue by armeniopinto** [BradenM/micropy-cli#345]
Hello,

I've just started using `micropy-cli` and it has been a great experience: smooth and clean. The only problem that I have is that Pylance is complaining that it can't find definitions for common Python functions - none of them is being found! Do you know what I might be missing here? Thank you!

**Comment by armeniopinto** [comment]
Hello again,

I installed `micropy-cli` on another system, in a completely clean VSC installation, and it has the same problem.

**Comment by BradenM** [comment]
Hi @armeniopinto 

Thanks for the reports. Micropy currently does not have templating support for pylance built in, unfortunately. (Maybe be wip, see #306). 

See #152 for some workarounds to make it work for now though.

**Comment by armeniopinto** [comment]
Hello, makes sense, thank you!

**Comment by BradenM** [comment]
Closed in #379
