### ISSUE TITLE
<SYMLINKD> is missing when make a git Clone

### ISSUE THREAD

**Issue by fpe** [BradenM/micropy-cli#38]
Hi
When I get an GIT Clone of my project on new PC, the <SYMLINKD> for -esp-micropython-1.11.0 and micropython is not created.

**Comment by BradenM** [comment]
Hi @fpe,

Strange. I can't seem to reproduce it on my end.
If it exists, try removing the copied projects `.micropy` folder and re-running `micropy`.

Do you mind providing me with a copy of your `$HOME/.micropy/micropy.log` file? 
Also, if its public, mind providing me a link to the repo your using?

Going to need a bit more information to get to the bottom of this one :)

**Comment by fpe** [comment]
First, thank you for your response.
I have now deleted the .micropy folder and run "micropy install" in cmd as admin, and it worked and everything is in place now. After looking at it a little close, I can see that on it I am called "fpe" and on the other I am called "Flemm". I enclose micropy.log as well as the link to github.

https://flemmingpetersen.visualstudio.com/DefaultCollection/AutomaticPlantBox/_git/AutomaticPlantBox

Thanks for the help

Best regrades
Flemming Petersen


________________________________
Fra: Braden Mars <notifications@github.com>
Sendt: 30. juli 2019 10:51
Til: BradenM/micropy-cli <micropy-cli@noreply.github.com>
Cc: Flemming Petersen <flemming_petersen@hotmail.com>; Mention <mention@noreply.github.com>
Emne: Re: [BradenM/micropy-cli] <SYMLINKD> is missing when make a git Clone (#38)


Hi @fpe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffpe&data=02%7C01%7C%7Ce0a88c4457004ba7443f08d714cb1485%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637000734759842657&sdata=DBFva7Ol9F4NmPk2B9bKp2iWsb8mu%2Fqrx5kETM5gkBU%3D&reserved=0>,

Strange. I can't seem to reproduce it on my end.
If it exists, try removing the copied projects .micropy folder and re-running micropy.

Do you mind providing me with a copy of your $HOME/.micropy/micropy.log file?
Also, if its public, mind providing me a link to the repo your using?

Going to need a bit more information to get to the bottom of this one :)

**Comment by BradenM** [comment]
Glad to see you got it working.

For the record, I do not have permission to view the repo you linked, but since your issue has been resolved all is well. 

I will add a more descriptive error for Windows users when they try to execute micropy without the proper permissions to avoid any future confusion. Thanks!
