### ISSUE TITLE
Create Directory Junction instead making symbolic links on Windows

### ISSUE THREAD

**Issue by vbolshakov** [BradenM/micropy-cli#44]
Junction (mklink /J) can be made without administrative privileges on Windows.

**Comment by BradenM** [comment]
Thanks! I will definitely take a look at this when I get a chance today.

**Comment by Josverl** [comment]
mklink

For windows 10  users who have Developer Mode enabled, the mklink command will now successfully create a symlink even f the user is not running as an administrator.

You can go to the For developers page at any time to enable or disable Developer Mode: simply enter "for developers" into the Cortana search box in the taskbar.

**Comment by vbolshakov** [comment]
Hard link and Directory Junction differ. Directory Junction created without any problems

**Comment by vbolshakov** [comment]
X:\!(2019-08-30 17-50)>mklink /H B A
Access is denied.

X:\!(2019-08-30 17-50)>mklink /J B A
Junction created for B <<===>> A

**Comment by vbolshakov** [comment]
Also, when using Win API there is no problems to create Hard Link - i use Far (File and achieve manager) and able to create both without admin privileges.

**Comment by BradenM** [comment]
When I get to my desktop today, I'm thinking about implementing a fallback on windows like this:

```py
import ctypes

kdll = ctypes.windll.LoadLibrary("kernel32.dll")

kdll.CreateSymbolicLinkW(UR"<project_dir>\.micropy\some-stub-link", UR"<micropy_folder>\some-stub", 1)
```

Thoughts?

**Comment by vbolshakov** [comment]
Not work. Create Symlink only with administrative privileges.

**Comment by vbolshakov** [comment]
Ok. There is no easy way... Pywin32 ad requirement or https://github.com/juntalis/ntfslink-python that just copy part of Pywin32.

**Comment by BradenM** [comment]
Oh, for some reason I thought the `CreateSymbolicLinkW` method used a junction. 

I will take a look at `ntfslink-python`, thanks.
