### ISSUE TITLE
getting various errors

### ISSUE THREAD

**Issue by Mrqozy** [BradenM/micropy-cli#525]
**Describe the bug**
im getting many errors such as "Expected no arguments to "Pin" constructor"
led=Pin(2,Pin.OUT)

Expected 0 positional arguments
even for print function!

**Expected Behavior**
Pin requires positional arguments

**Current Behavior**
im getting many errors such as "Expected no arguments to "Pin" constructor"
led=Pin(2,Pin.OUT)
![image](https://github.com/BradenM/micropy-cli/assets/40011623/ef10def1-cf14-478f-9676-caa24b369cb5)

**Steps to Reproduce**

1. use pin constructor
2. use print function
3.

**Possible Solution**

**Logs**

**Context (Environment)**

* OS:
* Micropy Version:4.2.1
* Python Version: 3.11
* VSCode Version:1.81.1

**Comment by Mrqozy** [comment]
> @Mrqozy,
> 
> Hi. This gives very little to go off and I cannot help without more details. Please add logs as well as more context around what stubs you are using, what device you are using, your configuration, etc.

im using micropython-esp32-stubs and almost every other stub give "print" is not defined" and "range" is not defined" error.

im using esp32

pymakr.conf
{
    "address": "192.168.4.1",
    "username": "micro",
    "password": "python",
    "sync_folder": "src",
    "open_on_start": true,
    "safe_boot_on_upload": false,
    "py_ignore": [
        "pymakr.conf",
        ".vscode",
        ".gitignore",
        ".git",
        "project.pymakr",
        "env",
        "venv",
        ".python-version",
        ".micropy/",
        "micropy.json"
    ],
    "fast_upload": false
}

![image](https://github.com/BradenM/micropy-cli/assets/40011623/e7fd1656-c1ca-4a35-9663-2e9d46aac005)

**Comment by Mrqozy** [comment]
print and range are recognized after commenting out this line

**Comment by UchihaYuki** [comment]
> im getting many errors such as "Expected no arguments to "Pin" constructor"

Have you solved your problem? I have encountered the same thing.

**Comment by UchihaYuki** [comment]
Instead of using `esp32-micropython-1.15.0` as the stubs of my project, I switch to  the following:
```json
"stubs": {
    "micropython-esp32-stubs": "1.19.1.post13",
    "micropython-stdlib-stubs": "0.9.0"
}
```
Everything works now. But I still have other problems.

**Comment by Mrqozy** [comment]
> > im getting many errors such as "Expected no arguments to "Pin" constructor"
> 
> Have you solved your problem? I have encountered the same thing.

Like I mentioned comment these lines in the settings.json under the folder .vscode


For pwm error you can just type next to the error line #type: ignore

This will tell pylance to ignore the error.

It's not a perfect solution but it's a start, until now the creators of this resp. didn't reply again even after I provided the info they asked for.

**Comment by Mrqozy** [comment]
> > im getting many errors such as "Expected no arguments to "Pin" constructor"
> 
> Have you solved your problem? I have encountered the same thing.

![image](https://github.com/BradenM/micropy-cli/assets/40011623/091c7354-29d6-403e-99cc-234953d42940)
this is the fix, frequency is not positional argument but a keyword one

**Comment by Mrqozy** [comment]
sorry for the mistake i just had to use a keyword argument for the frequency not a positional argument
