### ISSUE TITLE
all files have been uploaded to board

### ISSUE THREAD

**Issue by UchihaYuki** [BradenM/micropy-cli#526]
I used _micropy-cli 4.2.2_ to create a project with all the features ticked. When I use pymakr to upload my project to esp32 board, all files including those under .micropy have been uploaded.

I think that's because the option `sync_folder` of _pymakr.conf_ is deprecated.

Is there any solution to this?

**Comment by BradenM** [comment]
Hi @UchihaYuki. Thanks for the report, but please see #312
