### ISSUE TITLE
Import "bluetooth" could not be resolved

### ISSUE THREAD

**Issue by UchihaYuki** [BradenM/micropy-cli#534]
I can import machine, micropython, etc., but when I import bluetooth, vscode complains that 
> Import "bluetooth" could not be resolved

I use the following two stub:
```json
{
    "stubs": {
        "micropython-esp32-stubs": "1.19.1.post13",
        "micropython-stdlib-stubs": "0.9.0"
    },
    
}
```

**Comment by BradenM** [comment]
Hi @UchihaYuki.

Please share the information requested in the bug report template, as this snippet is not quite enough to go off of here.
