### ISSUE TITLE
Improve pylint path syntax and add ./src/lib

### ISSUE THREAD

**Issue by Josverl** [BradenM/micropy-cli#96]
Hi Braden,

I would like to suggest :

1. a change in syntax to the generated `.pylintrc` file to make it cleared to read and modify.
2. the addition of src/lib path as this is commonly used 

**current syntax (windows paths )** 
``` ini
[MASTER]
# Loaded Stubs:  esp32-micropython-1.11.0 
init-hook='import sys;sys.path.insert(1, ".micropy\\BradenM-micropy-stubs-7a7d171\\frozen");sys.path.insert(1, ".micropy\\BradenM-micropy-stubs-452a204\\frozen");sys.path.insert(1, ".micropy\\BradenM-micropy-stubs-7a7d171\\stubs");sys.path.insert(1,"src\\lib");sys.path.insert(1,"src\\font")'

...
```

**new [syntax](https://stackoverflow.com/questions/7376019/list-extend-to-index-inserting-list-elements-not-only-to-the-end/7376026#7376026)** 
``` ini
[MASTER]
# Loaded Stubs:  esp32-micropython-1.11.0 
init-hook='import sys;sys.path[1:1] = ["src/lib", "src/fonts", ".micropy/BradenM-micropy-stubs-7a7d171/frozen", ".micropy/BradenM-micropy-stubs-452a204/frozen", ".micropy/BradenM-micropy-stubs-7a7d171/stubs",".micropy/thermo"]'
# Note:  when adding paths; also add these paths to: VSCode Preferences > Workspace > python.autoComplete.extraPaths

...
```
The new syntax has the paths in the right order , is shorter, is simpler to extend with additional paths.

For me this helps in organizing my modules. I think this should be useful to others as well.

/Jos

**Comment by BradenM** [comment]
Sure, I like this idea. I could also add an additional config option `extraPaths` that would take an array of paths to add to `.pylintrc` and `python.autoComplete.extraPaths`.

Thoughts?

**Comment by Josverl** [comment]
yes, such an extrapaths would be a nice to have.
i think documentation is also relvant if adding that , as it haunted me for quite some time why my `src/lib` folder was not included while the `scr` folder was.
it seems that the Python Language Service has some magic to add a scr folder to the extrapaths even if yo do not specify it.

**Comment by BradenM** [comment]
Agreed. Documentation definitely needs some work. Will try and update it soon. Have not added the configuration option yet, but would love to hear your thoughts on #97. Thanks.
